app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 5eb1997c0831bf0a063b8414b64aaf26da73e29e
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: 3513aabc0c925cb0842abb6d87a777e8e3d14057
    url: api.nasa.n0b.me
