app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: e41465e437d86d7e31f4b8a0d1d42bee7a5f822a
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: 97bd2163f1d4aee1ab1fd8fb5588f2d38599dcd0
    url: api.nasa.n0b.me
