app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 2b5dc87a2be0bf3f7772de3fb640ee0deb130bcf
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: ee848195df53fc8fc896b61e55bf4cf7c63d0695
    url: api.nasa.n0b.me
