app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: ae831d5d1939e5b8866fcf1ff464d8b336c6ab85
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: 58e47598f4603a2e755af22c0ca3e5b3d2044c16
    url: api.nasa.n0b.me
