app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 9e601582da0b23ae01fc253e1dbe42e8c32c13ef
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: f412a5fe10130e04b0b1a84de0a99cd0436f9511
    url: api.nasa.n0b.me
