app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 30583bcaace03c8ce2d230d3058dfe76c907b60f
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: be99b9a006a3f3737e414c135edf21c6c9ff1a50
    url: api.nasa.n0b.me
