app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: ae831d5d1939e5b8866fcf1ff464d8b336c6ab85
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: f412a5fe10130e04b0b1a84de0a99cd0436f9511
    url: api.nasa.n0b.me
