app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: e41465e437d86d7e31f4b8a0d1d42bee7a5f822a
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: 920f6ca3c207239fb195d3c80429dd0ad98e99f5
    url: api.nasa.n0b.me
