app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 53f462fba4a97ae687f80b556722030a7580b950
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: 3146130ff7008a0bf97fbd09303144679b0b3b4f
    url: api.nasa.n0b.me
