app:
  frontend:
    image:
      repo: justin89721/nasa-fire-frontend
      tag: 30583bcaace03c8ce2d230d3058dfe76c907b60f
    url: nasa.n0b.me
  backend:
    image:
      repo: justin89721/nasa-fire-backend
      tag: e5523cef1c5e04a19bcba364f2b17d6f157f6410
    url: api.nasa.n0b.me
